stages:
  - build
  - test
  - deploy
 
build_linux:
  stage: build
  except: 
  - /latest/
  tags:
  - ubuntu1804
  before_script:
    - apt-get update
    - apt-get install -y tzdata
    - apt-get install -y cmake
    - apt-get install -y libpcl-dev
    - apt-get install -y python3-pip
  script:
    - mkdir -p build
    - mkdir -p dist-ubuntu1804
    - cd build
    - cmake ..
    - make
    - make test || cat Testing/Temporary/LastTest.log
    - make install DESTDIR=../dist-ubuntu1804
    - cd ..
    - tar --directory dist-ubuntu1804/usr/local -cvaf cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz .
    - touch successful.tmp
  after_script:
    - if [ ! -e successful.tmp -a -e build/Testing/Temporary/LastTest.log ]; then cat build/Testing/Temporary/LastTest.log; fi
  artifacts:
    paths:
      - cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz
      
build_osx:
  stage: build
  except: 
  - /latest/
  tags:
  - osx1014
#  before_script:
#    - brew install cmake || brew upgrade cmake
#    - brew install pcl || brew upgrade pcl
#    - brew install python3 || brew upgrade python3
  script:
    - mkdir -p build
    - mkdir -p dist-osx1014
    - cd build
    - cmake ..
    - make
    - make test
    - make install DESTDIR=../dist-osx1014
    - cd ..
    - tar --directory dist-osx1014/usr/local -z -cvf cwipc_util_osx1014_$CI_COMMIT_TAG.tgz .
    - touch successful.tmp
  after_script:
    - if [ ! -e successful.tmp -a -e build/Testing/Temporary/LastTest.log ]; then cat build/Testing/Temporary/LastTest.log; fi
  artifacts:
    paths:
      - cwipc_util_osx1014_$CI_COMMIT_TAG.tgz
      
build_win:
  stage: build
  except: 
  - /latest/
  tags:
  - win10
  script:
    - mkdir -p build
    - rm -rf /cygdrive/c/dist-win
    - mkdir -p /cygdrive/c/dist-win/installed
    - export ziplocation=$(pwd)/cwipc_util_win1064_$CI_COMMIT_TAG.zip
    - cd build
    - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="C:/dist-win/installed"
    - cmake --build . --config Release
    - cmake --build . --config Release --target RUN_TESTS
    - rm -rf /cygdrive/c/dist-win
    - mkdir -p /cygdrive/c/dist-win/installed
    - cmake --build . --config Release --target INSTALL
    - (cd /cygdrive/c/dist-win && zip -r $ziplocation installed)
    - touch successful.tmp
  after_script:
    - if [ ! -e successful.tmp -a -e build/Testing/Temporary/LastTest.log ]; then cat build/Testing/Temporary/LastTest.log; fi
  artifacts:
    paths:
      - cwipc_util_win1064_$CI_COMMIT_TAG.zip
      
deploy_all:
  stage: deploy
  tags:
  - linux
  only: 
  - tags
  except: 
  - /latest/
  dependencies: 
  - build_linux
  - build_osx
  - build_win
  before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - mkdir deployment-helpers
  - cd deployment-helpers
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@baltig.viaccess-orca.com:8443/VRT/deployment-group/Deployment
  - python3 -m pip install "scikit-learn>=0.23,!=0.24.0"
  - python3 -m pip install -r Deployment/scripts/requirements.txt
  - cd ..
  script:
    - mkdir deliverables
    - mv cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip deliverables
    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --notag cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip
      
deploy_all_untagged:
  stage: deploy
  tags:
  - linux
  except: 
  - tags
  - /latest/
  dependencies: 
  - build_linux
  - build_osx
  - build_win
  before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - mkdir deployment-helpers
  - cd deployment-helpers
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@baltig.viaccess-orca.com:8443/VRT/deployment-group/Deployment
  - python3 -m pip install -r Deployment/scripts/requirements.txt
  - cd ..
  script:
    - mkdir deliverables
    - mv cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip deliverables
    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --tag_name latest --release_name latest --deleterelease || true
    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --tag_name latest --release_name latest --deletetag || true
    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --tag_name latest --release_name latest --branch_to_tag "$CI_COMMIT_REF_NAME" cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip
