language: cpp
matrix:
    include:
        - os: linux
          dist: xenial
          before_install:
            - sudo apt-get update
            - sudo apt-get install libflann1.8 libflann-dev libboost1.58-all-dev
            - wget http://launchpadlibrarian.net/209530212/libeigen3-dev_3.2.5-4_all.deb
            - sudo dpkg -i libeigen3-dev_3.2.5-4_all.deb
            - wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.1.tar.gz
            - tar -xf pcl-1.8.1.tar.gz
            - cd pcl-pcl-1.8.1 && mkdir build && cd build
            - cmake ..
            - make
            - sudo make install
script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - make test
