language: cpp
matrix:
    exclude:
        - os: linux
          dist: xenial
          before_install:
            - sudo apt-get update
            - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
            - sudo apt-get install libusb-1.0-0-dev libusb-dev libudev-dev
            - sudo apt-get install mpi-default-dev openmpi-bin openmpi-common  
            - sudo apt-get install libflann1.8 libflann-dev
            - sudo apt-get install libeigen3-dev
            - sudo apt-get install libboost-all-dev
            - sudo apt-get install libvtk5.10-qt4 libvtk5.10 libvtk5-dev
            - sudo apt-get install libqhull* libgtest-dev
            - sudo apt-get install freeglut3-dev pkg-config
            - sudo apt-get install libxmu-dev libxi-dev 
            - sudo apt-get install mono-complete
            - sudo apt-get install qt-sdk openjdk-8-jdk openjdk-8-jre
            - wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.1.tar.gz
            - tar -xf pcl-1.8.1.tar.gz
            - cd pcl-pcl-1.8.1 && mkdir build && cd build
            - cmake ..
            - make
            - sudo make install
    include:
        - os: osx
          osx_image: xcode10
          addons:
            homebrew:
                update: true
                packages:
                - cmake
                - pcl        
script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - make test
